### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by hoky19** [Doodlister/inviter#1]
感谢分享~还想问下答题平台 根据手机号获取验证码、登录、绑定邀请码这些接口是怎么获取到的呢？

**Comment by JairoSun** [comment]
可以用fiddler对app进行抓包得到。

**Comment by MonkeyShawn** [comment]
请问西瓜可以同理做吗？

**Comment by jingkegit** [comment]
我这边 java.lang.NoSuchMethodError: org.junit.platform.commons.util.ClassUtils.isKotlinClass(Ljava/lang/Class;) 错误

**Comment by JairoSun** [comment]
@MonkeyShawn 西瓜的同理可以做，但是西瓜加密比较多，所以我只分析了一下登录的过程，具体的绑定验证码的过程的加密算法我还没有看。
登录过程需要传递 手机号 和 验证码两个参数。西瓜都已加密，具体的加密算法我在cn.doodlister.utils.WatermelonUtils类下的encryptWithXor中给出了。

**Comment by JairoSun** [comment]
@jingkegit 可能是缺少junit的包。 您可以吧Main方法中的@Test注解删掉。自己写一个main方法调用 相应的函数运行。

**Comment by MonkeyShawn** [comment]
期待出个西瓜的呀

**Comment by hoky19** [comment]
了解，学习了~
