### ISSUE TITLE
ItemId是如何设置的，提示报错？

### ISSUE THREAD

**Issue by Mr-houzi** [Doodlister/inviter#3]
ItemId是如何设置的，提示报错？

**Comment by JairoSun** [comment]
ItemId 在cn.doodlister.task 包下的CDDHTask.java 和 ZSTask.java 中都已经内置常量。
内置了速码 （SM_ITEM_ID） 和 易码  （YM_ITEM_ID）两个平台的itemid

**Comment by Mr-houzi** [comment]
```
public static void main(String[] args){
        Main main = new Main();
        ZSTask zstask = new ZSTask();
        main.runTask("4REZD",5,zstask,"13415");
    }
```
runTask第三个参数传入错误是什么问题呢？

**Comment by MonkeyShawn** [comment]
第三个参数要传入类对象

**Comment by Mr-houzi** [comment]
@MonkeyShawn  我new了ZSTask类的对象传入，然后提示报错cannot resolve constructor，是ZTask()没有定义参数吗？如果是的话，该如何定义？

**Comment by MonkeyShawn** [comment]
首先，ZSTask类没有无参的构造方法，其次，runTask第三个参数需要的是class类对象

**Comment by Mr-houzi** [comment]
报错Too many characters in character literal

![问题截图](https://user-images.githubusercontent.com/26339918/35208951-c5e2c0e6-ff85-11e7-8a55-f72fb7c6039c.png)

@MonkeyShawn

**Comment by JairoSun** [comment]
@Mr-houzi  
mian.runTask("4REZD",5,ZSTask.class,ZSTask.YM_ITEM_ID);

**Comment by Mr-houzi** [comment]
还是出现报错问题
![ 报错截图](https://user-images.githubusercontent.com/26339918/35210258-774f867e-ff8c-11e7-826a-b9b224c584bd.png)

**Comment by zhangkre** [comment]
有没有西瓜的啊？
